### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Ankit-Vohra** [KaihuaTang/Scene-Graph-Benchmark.pytorch#67]
## ❓ Questions and Help
I am facing this error while implementing SGGDet on custom images. Can you please help me with this?

File "/home/dell-7559/Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/data/datasets/visual_genome.py", line 63, in <listcomp>
    self.filenames = [self.filenames[i] for i in np.where(self.split_mask)[0]]
IndexError: list index out of range

**Comment by KaihuaTang** [comment]
I've just fixed this bug. You can directly comment out lines 52-64 in this file (visual_genome.py) to solve the issue.

**Comment by KaihuaTang** [comment]
sorry, comment out lines 52-64 won't solve the problem. You have to set up the dataset (follow https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/master/DATASET.md) even to run SGGDet on custom images, because some VG statistics information are used in the model.

**Comment by ajeetksingh** [comment]
Hi Kai,

Thanks for the reply. I was also trying to debug the aforementioned issue.

I just wanted to know if we ever need to uncomment these lines while we finetune/train from scratch the model?

**Comment by liuhl-source** [comment]
> ## ❓ Questions and Help
> 
> I am facing this error while implementing SGGDet on custom images. Can you please help me with this?
> 
> File "/home/dell-7559/Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/data/datasets/visual_genome.py", line 63, in
> self.filenames = [self.filenames[i] for i in np.where(self.split_mask)[0]]
> IndexError: list index out of range

Hi, have you fixed this bug? #69

**Comment by KaihuaTang** [comment]
My recent commit should fix the problem. https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/commit/81714a337ada463f428b2d0a1521730c5c597571

**Comment by YvonneZhao0305** [comment]
> My recent commit should fix the problem. [81714a3](https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/commit/81714a337ada463f428b2d0a1521730c5c597571)

Hi, I met the same problem, and I used the newest commit [1b955c6](https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/commit/1b955c608aa5c93ce25ee861bb60dea066f45f55#diff-a3e17e5e7b489553693b88e1f4f743564d8fcff78091374ad07df1b23c35aef9)


>   File "/home/xxx/Project/Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/data/datasets/visual_genome.py", line 66, in <listcomp>
    self.filenames = [self.filenames[i] for i in np.where(self.split_mask)[0]]
IndexError: list index out of range

**Comment by Sunting78** [comment]
> > My recent commit should fix the problem. [81714a3](https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/commit/81714a337ada463f428b2d0a1521730c5c597571)
> 
> Hi, I met the same problem, and I used the newest commit [1b955c6](https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/commit/1b955c608aa5c93ce25ee861bb60dea066f45f55#diff-a3e17e5e7b489553693b88e1f4f743564d8fcff78091374ad07df1b23c35aef9)
> 
> > File "/home/xxx/Project/Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/data/datasets/visual_genome.py", line 66, in 
> > self.filenames = [self.filenames[i] for i in np.where(self.split_mask)[0]]
> > IndexError: list index out of range

Me too. Have you already soloved?

**Comment by winnechan** [comment]
The new commint https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/commit/81714a337ada463f428b2d0a1521730c5c597571 does not resolve the problem for me? It seems that somewhere before the line 'data_loaders_val = make_data_loader(cfg, mode="test", is_distributed=distributed)' in tools/relation_test_net.py another dataloader of 'custom_eval False split train' is created.
